### ISSUE TITLE
BulkInserter buffer problem

### ISSUE THREAD

**Issue by droyad** [ronnieoverby/RonnieOverbyGrabBag#1]
The buffer is re-enumerated at line 127, meaning only about 1/2 the items are inserted

**Comment by droyad** [comment]
Suggested fix:
            var splits = Buffer(items, BufferSize).Select(b => b.ToArray()).ToArray();

```
            foreach (var split in splits)
            {
                foreach (var item in split)
                {
```

...
                    var bulkInsertEventArgs = new BulkInsertEventArgs<T>(split, _dt.Value);

**Comment by ronnieoverby** [comment]
What a dopey bug. Thanks.

You're suggested fix loads everything into memory. My fix only loads the current batch.

https://github.com/ronnieoverby/RonnieOverbyGrabBag/commit/9dbb3bd9947b1d63644b895d5d8022b0a07692b3
