### ISSUE TITLE
BulkInserter.cs and Inheritance?

### ISSUE THREAD

**Issue by ddivita** [ronnieoverby/RonnieOverbyGrabBag#2]
A while back I used a version of the BulkInserter.cs that used the Fasterflect library. I have a class that inherits from other classes and the new version of the BulkInserter fails on CreatePropertyGetter method because the type is not the DeclaringType. Going back to the old version using Fasterflect works without a hitch. Thought I would bring that up cause I ahve been using this code for quite some time and love it.

**Comment by ronnieoverby** [comment]
I can check into it if you send me a failing test.

**Comment by ronnieoverby** [comment]
I suspect this is the fix, though:

https://github.com/Core-Techs/Common/blob/master/CoreTechs.Common/Reflection/ReflectionExtensions.cs#L14

The project I've linked to has more goodies that I've written over the past few years.
